before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kasa
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: kanmu
      name: homebrew-tools
    homepage: https://github.com/kanmu/kasa
    description: CLI for esa.
    license: MIT
    install: |
      bin.install 'kasa'
